version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql_5.7
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=docker_db
      - MYSQL_ROOT_PASSWORD=root
    ports: 
      - 3307:3306
    volumes: 
      - dbdata:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    command: '--default-authentication-plugin=mysql_native_password'


volumes:
  dbdata:

networks:
  default:
    external:
      name: db-network
